// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace 精誠微雲_古皓宇sln.Models;

public partial class Account
{
    public int FId { get; set; }

    public string AccountGuid { get; set; }

    public string OwnerGuid { get; set; }

    public int? BranchId { get; set; }

    public int? AcctSerialId { get; set; }

    public int? AccountKind { get; set; }

    public bool? AccountStatus { get; set; }
}