// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace 精誠微雲_古皓宇sln.Models;

public partial class dbBankContext : DbContext
{
    public dbBankContext(DbContextOptions<dbBankContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Account> Accounts { get; set; }

    public virtual DbSet<NetBankUser> NetBankUsers { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Account>(entity =>
        {
            entity.HasNoKey();

            entity.Property(e => e.AccountGuid).HasMaxLength(50);
            entity.Property(e => e.AccountStatus).HasDefaultValueSql("((0))");
            entity.Property(e => e.AcctSerialId).HasColumnName("AcctSerialID");
            entity.Property(e => e.BranchId).HasColumnName("BranchID");
            entity.Property(e => e.FId)
                .ValueGeneratedOnAdd()
                .HasColumnName("fId");
            entity.Property(e => e.OwnerGuid).HasMaxLength(50);
        });

        modelBuilder.Entity<NetBankUser>(entity =>
        {
            entity.HasKey(e => e.UserGuid);

            entity.Property(e => e.UserGuid).HasMaxLength(50);
            entity.Property(e => e.FId)
                .ValueGeneratedOnAdd()
                .HasColumnName("fId");
            entity.Property(e => e.IsAlive).HasDefaultValueSql("((1))");
            entity.Property(e => e.NationId)
                .HasMaxLength(50)
                .HasColumnName("NationID");
            entity.Property(e => e.Status).HasMaxLength(50);
            entity.Property(e => e.UserName).HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}