// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace 精誠微雲_古皓宇sln.Models;

public partial class NetBankUser
{
    public int FId { get; set; }

    public string UserGuid { get; set; }

    public string NationId { get; set; }

    public int? UserKind { get; set; }

    public string UserName { get; set; }

    public string Status { get; set; }

    public bool? IsAlive { get; set; }
}